arch:
  - arm64
before_install:
  - sudo apt-get install boinc-client boinc-manager
script:
  - sudo pkill boinc
  - sudo boinc --attach_project https://boinc.thesonntags.com/collatz/ 10bda4e24faf95d2fe65e873b9f3517e -dir /var/lib/boinc-client
