arch:
  - arm64
before_install:
  - sudo apt-get install boinc-client boinc-manager
script:
  - sudo pkill boinc
  - sudo boinc --attach_project https://boinc.thesonntags.com/collatz/ 2164609_4bb5651265f39cd99b07336801baf0e3 -dir /var/lib/boinc-client
